networks:
  vnet:


volumes:
  db-data:
    external: true
  broker-log:
  certbot-etc:
  certbot-var:


services:

  broker:
    image: eclipse-mosquitto
    restart: always
    networks:
      - vnet
    volumes:
      - broker-log:/mosquitto/log
    ports:
      - "0.0.0.0:1883:1883"

  db:
    image: db
    restart: always
    networks:
      - vnet
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
      - "0.0.0.0:33060:3306"

  restapi:
    image: restapi
    restart: always
    depends_on:
      - db
      - broker
    networks:
      - vnet
    ports:
      - "127.0.0.1:8000:8000"

  nginx:
    image: nginx:stable
    restart: always
    depends_on:
      - restapi
    volumes:
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www/sslv1:/etc/nginx/sslv1
      - ./www/webroot:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - vnet
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:8080:8080"

  # certbot:
  #   image: certbot/certbot
  #   networks:
  #     - vnet
  #   volumes:
  #     - ./www/webroot:/usr/share/nginx/html:rw
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html --email marek.tews@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d krw.ddns.net -d www.krw.ddns.net