INSERT INTO `Zbory` (`number`, `name`) VALUES(14357, 'Białobrzegi');
INSERT INTO `Zbory` (`number`, `name`) VALUES(2063, 'Ciechanów-Aleksandrówka');
INSERT INTO `Zbory` (`number`, `name`) VALUES(15214, 'Ciechanów-Podzamcze');
INSERT INTO `Zbory` (`number`, `name`) VALUES(14076, 'Góra Kalwaria');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1479, 'Grodzisk Mazowiecki');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1628, 'Grójec');
INSERT INTO `Zbory` (`number`, `name`) VALUES(18655, 'Izabelin');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1305, 'Łomianki');
INSERT INTO `Zbory` (`number`, `name`) VALUES(15032, 'Małocice');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1420, 'Milanówek');
INSERT INTO `Zbory` (`number`, `name`) VALUES(16998, 'Mszczonów');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1677, 'Nadarzyn');
INSERT INTO `Zbory` (`number`, `name`) VALUES(17350, 'Nasielsk');
INSERT INTO `Zbory` (`number`, `name`) VALUES(16980, 'Nowe Miasto n. Pilicą');
INSERT INTO `Zbory` (`number`, `name`) VALUES(2055, 'Nowy Dwór Mazowiecki');
INSERT INTO `Zbory` (`number`, `name`) VALUES(18713, 'Piaseczno');
INSERT INTO `Zbory` (`number`, `name`) VALUES(17012, 'Płońsk');
INSERT INTO `Zbory` (`number`, `name`) VALUES(17053, 'Pruszków-Północ');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1412, 'Pruszków-Południe');
INSERT INTO `Zbory` (`number`, `name`) VALUES(13946, 'Przasnysz');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1446, 'Sochaczew');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1362, 'Warszawa-Bemowo');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1263, 'Warszawa-Bielany');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1693, 'Warszawa-Centrum');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1313, 'Warszawa-Chomiczówka');
INSERT INTO `Zbory` (`number`, `name`) VALUES(9494, 'Warszawa-Gruziński');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1370, 'Warszawa-Jelonki');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1354, 'Warszawa-Koło');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1206, 'Warszawa-Mirów');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1537, 'Warszawa-Mokotów');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1214, 'Warszawa-Muranów');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1651, 'Warszawa-Natolin');
INSERT INTO `Zbory` (`number`, `name`) VALUES(14043, 'Warszawa-Nowolipki');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1560, 'Warszawa-Nowy Służewiec');
INSERT INTO `Zbory` (`number`, `name`) VALUES(15313, 'Warszawa-Nowy Świat');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1511, 'Warszawa-Ochota');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1503, 'Warszawa-Rakowiec');
INSERT INTO `Zbory` (`number`, `name`) VALUES(18572, 'Warszawa-Raszyn');
INSERT INTO `Zbory` (`number`, `name`) VALUES(2113, 'Warszawa-Tarchomin');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1594, 'Warszawa-Ursynów');
INSERT INTO `Zbory` (`number`, `name`) VALUES(17574, 'Warszawa-Wesoła');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1636, 'Warszawa-Wilanów');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1230, 'Warszawa-Żoliborz');
INSERT INTO `Zbory` (`number`, `name`) VALUES(13508, 'Ząbki');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1685, 'Zalesie Górne');
INSERT INTO `Zbory` (`number`, `name`) VALUES(1438, 'Żyrardów-Północ');
INSERT INTO `Zbory` (`number`, `name`) VALUES(15933, 'Żyrardów-Południe');